### ISSUE TITLE
Proper language support

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/fuksilaiterekisteri#97]
- [ ] store copy text outside code (db, language file?)
- [ ] store preferred language of user in db
- [ ] provide text in preferred language (fi/en)
- [ ] add sv support
